Id b 4
Alekskas75/PetFamily pull request #4
Opened 2024-08-09 09:44 UTC by Alekskas75

2024-08-09 10:19 UTC, KirillSachkov requested changes

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Pet.cs
> +        public int Id { get; set; }
Должен быть Guid

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Pet.cs
> +        public string PetName { get; set; }
Не PetName, а Name

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Pet.cs
> +        public string PetType { get; set; }
Лучше Species

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Pet.cs
> +        public string PetDescription { get; set; }
Не нужно везде подставлять Pet, у тебя и так эти свойства у животного

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Pet.cs
> +        public string Status { get; set; }  //Статус помощи - Нуждается в помощи/Ищет дом/Нашел дом
Сделай из этого enum

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Pet.cs
> +        public string HelpDetails { get; set; }  //Реквизиты для помощи (у каждого реквизита будет название и описание, как сделать перевод), поэтому нужно сделать отдельный класс для реквизита
Для реквезитов сделай отдельный класс и здесь должен быть список реквезитов

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Volunteer.cs
> +        public string DetailsForHelp { get; set; }
Для реквезитов сделай отдельный класс и здесь должен быть список реквезитов

2024-08-09 10:19 UTC, KirillSachkov commented on PetFamily.Domain/Volunteer.cs
> +        public string SocialNetworks { get; set; }
Для социальный сетей должен быть отдельный класс и здесь должен быть список социальных сетей

2024-08-09 12:47 UTC, YADARAN1 approved these changes

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Pet.cs
> +        public string TelephoneNumberForContacting { get; set; }
Просто PhoneNumber

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/HelpDetails.cs
> +        public Guid Id { get; set; }
У свойств везде private set

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Pet.cs
> +        public string Name { get; set; }
У свойств везде private set

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/SocialNetworks.cs
> +        public string Name { get; set; }
У свойств везде private set

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/PetPhoto.cs
> +        public Guid Id { get; set; }
У свойств везде private set

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Volunteer.cs
>          public string TelephoneNumber { get; set; }
Просто PhoneNumber

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Volunteer.cs
> +        public int Guid { get; set; }
Ошибка, Guid Id, а не int Guid + у свойств везде private set

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/HelpDetails.cs
> +    public class HelpDetails
Можно переименовать на Requisite, чтобы было понятнее

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Pet.cs
>          public bool Neutered { get; set; }     // Кастрирован?
Neutered замени на IsCastrated

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Pet.cs
>          public bool Vaccinated { get; set; }  //Вакцинирован?
Vaccinated измени на IsVaccinated

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Pet.cs
> +        public List<HelpDetails> DetailsForHelp { get; set; }  //Реквизиты для помощи (у каждого реквизита будет название и описание, как сделать перевод), поэтому нужно сделать отдельный класс для р
Изменить public List<HelpDetails> DetailsForHelp { get; set; } на public List<Requisites> Requisites

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/PetPhoto.cs
>          public bool MainPhoto { get; set; }
MainPhoto замени на IsMainPhoto

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Volunteer.cs
> +        public List<HelpDetails> DetailsForHelp { get; set; }
Изменить public List<HelpDetails> DetailsForHelp { get; set; } на public List<Requisites> Requisites

2024-08-09 12:47 UTC, YADARAN1 commented on PetFamily.Domain/Volunteer.cs
>          public List<Pet> ListOfPets { get; set; }
ListOfPets измени на Pets

2024-08-10 06:18 UTC, merged

2024-08-10 08:42 UTC, YADARAN1 commented on PetFamily.Domain/Volunteer.cs
> +        public int Guid { get; private set; }
тут ошибка, здесь int Guid, а не Guid Id

2024-08-10 08:42 UTC, YADARAN1 commented on PetFamily.Domain/Volunteer.cs
> +        public string TelephoneNumber { get; private set; }
Здесь просто PhoneNumber